import CTABottomSection from "@/components/homepage/CTABottomSection";
import HeroSection from "@/components/homepage/HeroSection";
import InsightsSection from "@/components/homepage/InsightsSection";
import OfferingSection from "@/components/homepage/OfferingSection";
import SubHeroSection from "@/components/homepage/SubHeroSection";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HeroSection />
			<SubHeroSection />
			<InsightsSection />
			<OfferingSection />
			<CTABottomSection />
		</>
	);
}
