import HeroSection from "@/components/homepage/HeroSection";
import SubHeroSection from "@/components/homepage/SubHeroSection";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<HeroSection />
			<SubHeroSection />
		</>
	);
}
